-- AlterTable
ALTER TABLE `foods` ADD COLUMN `img1` VARCHAR(191) NULL,
    ADD COLUMN `img10` VARCHAR(191) NULL,
    ADD COLUMN `img2` VARCHAR(191) NULL,
    ADD COLUMN `img3` VARCHAR(191) NULL,
    ADD COLUMN `img4` VARCHAR(191) NULL,
    ADD COLUMN `img5` VARCHAR(191) NULL,
    ADD COLUMN `img6` VARCHAR(191) NULL,
    ADD COLUMN `img7` VARCHAR(191) NULL,
    ADD COLUMN `img8` VARCHAR(191) NULL,
    ADD COLUMN `img9` VARCHAR(191) NULL;
